import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { openDB } from 'idb';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API requests
registerRoute(
  ({ url }) => url.origin === 'https://story-api.dicoding.dev' && url.pathname.startsWith('/v1/stories'),
  new NetworkFirst({
    cacheName: 'api-stories-cache',
  })
);

// IndexedDB Helper for Service Worker Background Sync
const dbPromise = openDB('story-share-db', 1);

// Handle Background Sync
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-new-stories') {
    event.waitUntil(syncOutboxStories());
  }
});

async function syncOutboxStories() {
  const db = await dbPromise;
  const outboxStories = await db.getAll('outbox_stories');

  for (const story of outboxStories) {
    try {
      const formData = new FormData();
      formData.append('description', story.description);
      formData.append('photo', story.photo);
      if (story.lat && story.lon) {
        formData.append('lat', story.lat);
        formData.append('lon', story.lon);
      }

      const response = await fetch('https://story-api.dicoding.dev/v1/stories', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${story.token}`,
        },
        body: formData,
      });

      if (response.ok) {
        await db.delete('outbox_stories', story.id);
        
        // Show success notification
        self.registration.showNotification('Story Tersinkronisasi', {
          body: 'Story Anda yang dibuat saat offline telah berhasil diunggah.',
          icon: '/favicon.png'
        });
      }
    } catch (error) {
      console.error('Failed to sync story:', error);
    }
  }
}

// Handle Push Notifications
self.addEventListener('push', (event) => {
  if (event.data) {
    try {
      const text = event.data.text();
      const data = JSON.parse(text);
      const options = {
        body: data.options?.body || 'Anda mendapatkan notifikasi baru.',
        icon: '/favicon.png',
        data: data.options?.data || {}
      };
      event.waitUntil(
        self.registration.showNotification(data.title || 'Notification', options)
      );
    } catch (e) {
      console.error('Error parsing push data', e);
      // Fallback if not JSON
      event.waitUntil(
        self.registration.showNotification('Notification', {
          body: event.data.text(),
          icon: '/favicon.png'
        })
      );
    }
  }
});

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const storyId = event.notification.data?.id;
  
  if (storyId) {
    const targetUrl = `/#/stories/${storyId}`;
    event.waitUntil(
      clients.matchAll({ type: 'window' }).then((windowClients) => {
        // If app is already open, focus and navigate
        for (let client of windowClients) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.navigate(targetUrl);
            return client.focus();
          }
        }
        // If app is closed, open a new window
        if (clients.openWindow) {
          return clients.openWindow(targetUrl);
        }
      })
    );
  }
});
